name: CI/CD — Backend ECS

on:
  push:
    branches:
      - deploy

jobs:
  build-and-deploy:
    name: Build, Push y Deploy Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Login a Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build y Push — Despachos
        env:
          ECR_REGISTRY: 965615436594.dkr.ecr.us-east-1.amazonaws.com
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/proyecto-semestral-backend-despachos:$IMAGE_TAG -f proyecto-semestral-backend/Dockerfile proyecto-semestral-backend
          docker tag $ECR_REGISTRY/proyecto-semestral-backend-despachos:$IMAGE_TAG $ECR_REGISTRY/proyecto-semestral-backend-despachos:latest
          docker push $ECR_REGISTRY/proyecto-semestral-backend-despachos:$IMAGE_TAG
          docker push $ECR_REGISTRY/proyecto-semestral-backend-despachos:latest

      - name: Build y Push — Ventas
        env:
          ECR_REGISTRY: 965615436594.dkr.ecr.us-east-1.amazonaws.com
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/proyecto-semestral-backend-ventas:$IMAGE_TAG -f proyecto-semestral-backend/back-ventas/Dockerfile proyecto-semestral-backend/back-ventas
          docker tag $ECR_REGISTRY/proyecto-semestral-backend-ventas:$IMAGE_TAG $ECR_REGISTRY/proyecto-semestral-backend-ventas:latest
          docker push $ECR_REGISTRY/proyecto-semestral-backend-ventas:$IMAGE_TAG
          docker push $ECR_REGISTRY/proyecto-semestral-backend-ventas:latest

      - name: Deploy Despachos a ECS
        run: |
          aws ecs update-service \
            --cluster proyecto-semestral-cluster \
            --service despachos-service \
            --force-new-deployment \
            --region us-east-1

      - name: Deploy Ventas a ECS
        run: |
          aws ecs update-service \
            --cluster proyecto-semestral-cluster \
            --service ventas-service \
            --force-new-deployment \
            --region us-east-1
